# coding: utf-8

"""
    RAKIP Generic model

    TODO  # noqa: E501

    OpenAPI spec version: 1.0.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.predictive_model_general_information import PredictiveModelGeneralInformation  # noqa: E501
from swagger_client.rest import ApiException


class TestPredictiveModelGeneralInformation(unittest.TestCase):
    """PredictiveModelGeneralInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPredictiveModelGeneralInformation(self):
        """Test PredictiveModelGeneralInformation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.predictive_model_general_information.PredictiveModelGeneralInformation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
