# coding: utf-8

"""
    RAKIP Generic model

    TODO  # noqa: E501

    OpenAPI spec version: 1.0.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.dietary_assessment_method import DietaryAssessmentMethod  # noqa: E501
from swagger_client.rest import ApiException


class TestDietaryAssessmentMethod(unittest.TestCase):
    """DietaryAssessmentMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDietaryAssessmentMethod(self):
        """Test DietaryAssessmentMethod"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.dietary_assessment_method.DietaryAssessmentMethod()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
