# coding: utf-8

"""
    RAKIP Generic model

    TODO  # noqa: E501

    OpenAPI spec version: 1.0.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.dose_response_model_model_math import DoseResponseModelModelMath  # noqa: E501
from swagger_client.rest import ApiException


class TestDoseResponseModelModelMath(unittest.TestCase):
    """DoseResponseModelModelMath unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDoseResponseModelModelMath(self):
        """Test DoseResponseModelModelMath"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.dose_response_model_model_math.DoseResponseModelModelMath()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
