# coding: utf-8

"""
    RAKIP Generic model

    TODO  # noqa: E501

    OpenAPI spec version: 1.0.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.predictive_model_data_background import PredictiveModelDataBackground  # noqa: E501
from swagger_client.rest import ApiException


class TestPredictiveModelDataBackground(unittest.TestCase):
    """PredictiveModelDataBackground unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPredictiveModelDataBackground(self):
        """Test PredictiveModelDataBackground"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.predictive_model_data_background.PredictiveModelDataBackground()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
