# coding: utf-8

"""
    RAKIP Generic model

    TODO  # noqa: E501

    OpenAPI spec version: 1.0.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.predictive_model import PredictiveModel  # noqa: E501
from swagger_client.rest import ApiException


class TestPredictiveModel(unittest.TestCase):
    """PredictiveModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPredictiveModel(self):
        """Test PredictiveModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.predictive_model.PredictiveModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
