# coding: utf-8

"""
    RAKIP Generic model

    TODO  # noqa: E501

    OpenAPI spec version: 1.0.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.consumption_model_scope import ConsumptionModelScope  # noqa: E501
from swagger_client.rest import ApiException


class TestConsumptionModelScope(unittest.TestCase):
    """ConsumptionModelScope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConsumptionModelScope(self):
        """Test ConsumptionModelScope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.consumption_model_scope.ConsumptionModelScope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
