# coding: utf-8

"""
    RAKIP Generic model

    TODO  # noqa: E501

    OpenAPI spec version: 1.0.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.data_model_model_math import DataModelModelMath  # noqa: E501
from swagger_client.rest import ApiException


class TestDataModelModelMath(unittest.TestCase):
    """DataModelModelMath unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataModelModelMath(self):
        """Test DataModelModelMath"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.data_model_model_math.DataModelModelMath()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
