# coding: utf-8

"""
    RAKIP Generic model

    TODO  # noqa: E501

    OpenAPI spec version: 1.0.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.process_model_scope import ProcessModelScope  # noqa: E501
from swagger_client.rest import ApiException


class TestProcessModelScope(unittest.TestCase):
    """ProcessModelScope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProcessModelScope(self):
        """Test ProcessModelScope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.process_model_scope.ProcessModelScope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
