# coding: utf-8

"""
    RAKIP Generic model

    TODO  # noqa: E501

    OpenAPI spec version: 1.0.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.other_model_data_background import OtherModelDataBackground  # noqa: E501
from swagger_client.rest import ApiException


class TestOtherModelDataBackground(unittest.TestCase):
    """OtherModelDataBackground unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOtherModelDataBackground(self):
        """Test OtherModelDataBackground"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.other_model_data_background.OtherModelDataBackground()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
